2) passed all task
AntonPanchishko/CinemaProject pull request #1
Opened 2021-01-26 15:11 UTC by AntonPanchishko

2021-01-26 16:40 UTC, Fedich09 requested changes

2021-01-26 16:40 UTC, Fedich09 commented on pom.xml
>  </project>
add empty line please 
```suggestion
</project>
```

2021-01-26 16:40 UTC, Fedich09 commented on src/.travis.yml
> +    - $HOME/.m2
```suggestion
    - $HOME/.m2
```
here same situation with empty line

2021-01-26 16:40 UTC, Fedich09 commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert movie entity", e);
```suggestion
            throw new RuntimeException("Can't insert movie entity", e);
```
here we should throw our custom exception

2021-01-26 16:40 UTC, Fedich09 commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't get all movies from db", e);
same here

2021-01-26 16:40 UTC, Fedich09 commented on src/main/java/com/dev/cinema/model/Movie.java
> +public class Movie {
```suggestion
public class Movie {
```
add here @ Table(name = "movie")
it's necessary  to name our table with lower case

2021-01-26 16:40 UTC, Fedich09 commented on src/main/java/com/dev/cinema/util/HibernateUtil.java
> +            throw new RuntimeException("Cant creating session factory", e);
```suggestion
            throw new RuntimeException("Cant creating session factory", e);
```
here the same situation with custom exception

2021-01-26 16:40 UTC, Fedich09 commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
```suggestion
</hibernate-configuration>
```
add empty line please

2021-01-26 17:09 UTC, Fedich09 approved these changes

2021-01-27 07:15 UTC, Sofasmile requested changes

2021-01-27 07:15 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            movie.setId(itemId);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/homework/hibernate_01.html

2021-01-27 07:15 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new DataBindingException("Cant insert entity in db", e);
```suggestion
            throw new DataBindingException("Cant insert entity in db " + movie, e);
```

2021-01-27 07:15 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            session.close();
let's add checking for null here

2021-01-27 07:15 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +
remove the empty line at the beginning of the method

2021-01-27 08:27 UTC, Sofasmile requested changes

2021-01-27 08:27 UTC, Sofasmile commented on src/main/java/com/dev/cinema/util/HibernateUtil.java
> +            throw new DataBindingException("Cant creating session factory", e);
it isn't data problem, so let's throw RuntimeException here

2021-01-27 08:42 UTC, Sofasmile approved these changes

2021-01-27 09:01 UTC, merged