41) realized authentication from DB
AntonPanchishko/CinemaProject pull request #10
Opened 2021-02-21 17:08 UTC by AntonPanchishko

2021-02-21 23:37 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .and()
what are you authorizing here?

2021-02-21 23:37 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +        org.springframework.security.core.userdetails.User.UserBuilder builder =
move this to imports

2021-02-21 23:37 UTC, Max-Pochepets approved these changes

2021-02-22 08:44 UTC, RomanDubovskyi requested changes

2021-02-22 08:44 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .authorizeRequests()
```suggestion
                .authorizeRequests()
```

2021-02-22 08:44 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .anyRequest().authenticated()
let's add permitall for registration

2021-02-22 08:44 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +                    + " LEFT JOIN FETCH u.roles WHERE u.email = :email", User.class)
inner join would better here, there should not be situation when user doesn't have role

2021-02-22 08:44 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +            return session.createQuery("SELECT u FROM User u"
same here

2021-02-22 08:44 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +        com.dev.cinema.model.User user = userService.findByEmail(email).get();
let's throw UsernameNotFoundException instead of NoSuchElementException

2021-02-22 10:49 UTC, RomanDubovskyi requested changes

2021-02-22 10:49 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +                    + " LEFT JOIN FETCH u.roles WHERE u.email = :email", User.class)
you didnt fix this comment - change LEFT JOIN to JOIN and don't remove .setParameter()

2021-02-22 10:49 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +                    + " WHERE u.id = :id", User.class)
same here

2021-02-22 10:49 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/security/CustomUserDetailsService.java
> +        com.dev.cinema.model.User user = userService.findByEmail(email).get();
this comment wasn't fixed

2021-02-22 12:18 UTC, RomanDubovskyi approved these changes

2021-02-22 12:18 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.GET,"/movies/**").permitAll()
fix permissions according to the message that Sofia has written in general channel, rest seems to be good

2021-02-25 16:39 UTC, merged