12) added user model and connected with it staff, implement authentic…
AntonPanchishko/CinemaProject pull request #3
Opened 2021-02-02 15:03 UTC by AntonPanchishko

…ation service

2021-02-02 16:24 UTC, Max-Pochepets requested changes

2021-02-02 16:24 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +        user.setSalt(salt);
This should be done in [UserService](https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_05.html). It's not a part of DAO

2021-02-02 16:24 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +                    .createQuery("from User u where u.email =:email",
why do you need alias here?

2021-02-02 16:24 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/model/User.java
> +                + ", password='" + password + '\'' + '}';
You heard the man, there is a standard way to override basic methods.

2021-02-02 16:24 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +                + email + " and password " + password);
This is a matter of security, do not specify what did user input wrong here. In fact, if you show this message in the normal system - your password will be open for prying eyes.

2021-02-02 18:24 UTC, Max-Pochepets approved these changes
👍

2021-02-02 18:24 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +        throw new AuthenticationException("Cant find user with such email and password");
lets throw this ones. HINT combine checks

2021-02-03 11:17 UTC, dmytro-hryhoruk approved these changes

2021-02-03 11:17 UTC, dmytro-hryhoruk commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +            throw new AuthenticationException("Can't find user with such email " + email);
```suggestion
            throw new AuthenticationException("Can't find a user with such email or password");
```

2021-02-03 14:25 UTC, merged