16) added new models and connected with it services/Dao
AntonPanchishko/CinemaProject pull request #4
Opened 2021-02-03 14:25 UTC by AntonPanchishko

2021-02-03 18:29 UTC, Max-Pochepets requested changes

2021-02-03 18:29 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +            throw new DataBindingException("Can't add this shop cart to BD "
```suggestion
            throw new DataBindingException("Can't add to DB shop cart  "
```

2021-02-03 18:29 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +@Table(name = "shopping_cart")
```suggestion
@Table(name = "shopping_carts")
```
same with others

2021-02-03 18:29 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +    @Inject private TicketDao ticketDao;
```suggestion
    @Inject 
    private MovieSessionDao movieSessionDao;
    @Inject 
    private ShoppingCartDao shoppingCartDao;
    @Inject 
    private TicketDao ticketDao;
```

2021-02-03 18:29 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/Main.java
> +            e.printStackTrace();
I would not recommend to try-catch all of these. Save the result of `login()` to a variable and use it in `shoppingCarService`. But if you still want to keep it as it is - `e.printStackTrace()` is a bad practice. You can show the AuthenticationException message

2021-02-03 19:36 UTC, Max-Pochepets approved these changes

2021-02-03 19:36 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/Main.java
>              e.printStackTrace();
still, `e.printStackTrace()` - bad practice

2021-02-04 07:16 UTC, KseniiaMakarova requested changes

2021-02-04 07:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +
redundant empty line

2021-02-04 07:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
is it needed?

2021-02-04 07:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/Ticket.java
> +@Table(name = "ticket")
let's use either singular or plural for all table names

2021-02-04 07:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/security/AuthenticationServiceImpl.java
> +    @Inject private ShoppingCartService shoppingCartService;
```suggestion
    @Inject 
    private UserService userService;
    @Inject 
    private ShoppingCartService shoppingCartService;
```

2021-02-04 07:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +    private MovieSessionDao movieSessionDao;
do you use this?

2021-02-04 07:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +        ticketDao.add(ticket);
if there is no shopping cart for the user - we still save ticket to the db, is it ok?

2021-02-04 07:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCartByUser = getByUser(user);
do you need this?

2021-02-04 10:20 UTC, KseniiaMakarova approved these changes

2021-02-04 18:45 UTC, merged