22) solved task
AntonPanchishko/CinemaProject pull request #5
Opened 2021-02-04 18:47 UTC by AntonPanchishko

2021-02-04 19:51 UTC, vicire requested changes
Nice, but one remark

2021-02-04 19:51 UTC, vicire commented on src/main/java/com/dev/cinema/dao/impl/OrderDaoImpl.java
> +                    .createQuery("FROM Order o "
https://mateacademy.slack.com/archives/G01EHB8CWAE/p1612455330236200

2021-02-04 20:16 UTC, vicire approved these changes

2021-02-05 09:53 UTC, dmytro-hryhoruk approved these changes

2021-02-11 12:58 UTC, merged