30) added new controllers, and connected with it staff
AntonPanchishko/CinemaProject pull request #8
Opened 2021-02-16 14:26 UTC by AntonPanchishko

2021-02-16 18:43 UTC, Max-Pochepets requested changes

2021-02-16 18:43 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/controller/OrderController.java
> +                                        .getById(userId))));
Let's not do this ladder))

2021-02-16 18:43 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/controller/OrderController.java
> +    public OrderResponseDto completeOrder(@RequestParam Long userId) {
If I'm not mistaken, this must be POST method

2021-02-16 18:43 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/controller/OrderController.java
> +    public List<OrderResponseDto> getAllOrder(@RequestParam Long userId) {
```suggestion
    public List<OrderResponseDto> getOrderHistory(@RequestParam Long userId) {
```

2021-02-16 18:43 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/controller/ShoppingCartController.java
> +    public void add(@RequestParam Long userId, Long movieSessionId) {
```suggestion
    public void add(@RequestParam Long userId, @RequestParam Long movieSessionId) {
```
It won't work in other way

2021-02-16 18:43 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +            throw new DataBindingException("Can't find entity by id " + id, e);
```suggestion
            throw new DataBindingException("Can't find user by id " + id, e);
```

2021-02-16 18:43 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/model/dto/response/OrderResponseDto.java
> +    private List<Long> ticketsId;
```suggestion
    private List<Long> ticketIds;
```

2021-02-16 18:43 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/model/dto/response/ShoppingCartResponseDto.java
> +    private List<Long> ticketsId;
same

2021-02-16 19:58 UTC, Max-Pochepets approved these changes

2021-02-17 10:55 UTC, KseniiaMakarova requested changes

2021-02-17 10:55 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controller/AuthenticationController.java
> +    public void registration(@RequestBody UserRequestDto requestDto) {
```suggestion
    public void register(@RequestBody UserRequestDto requestDto) {
```
method names should be verbs

2021-02-17 10:55 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controller/AuthenticationController.java
> +    public AuthenticationController(AuthenticationService service) {
let's use annotation above the constructor everywhere

2021-02-17 10:55 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controller/ShoppingCartController.java
> +    public void add(@RequestParam Long userId, @RequestParam Long movieSessionId) {
```suggestion
    public void addSession(@RequestParam Long userId, @RequestParam Long movieSessionId) {
```

2021-02-17 10:55 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/OrderMapper.java
> +@Service
```suggestion
@Component
```
same for all mappers

2021-02-17 10:55 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/UserMapper.java
> +
redundant empty line

2021-02-17 10:55 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mapper/UserMapper.java
> +    public User fromDtoToObject(UserRequestDto userRequestDto) {
do we need this method?

2021-02-17 11:55 UTC, KseniiaMakarova approved these changes

2021-02-18 12:13 UTC, merged